version: '3.5'

services:
    nginx:
        image: nginx:1.15-alpine
        container_name: webproxy-nginx
        restart: on-failure:5
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/conf.d:/etc/nginx/conf.d
            - webproxy-vhost:/etc/nginx/vhost.d
            - webproxy-html:/usr/share/nginx/html
            - ./data/certs:/etc/nginx/certs:ro
            - ./data/htpasswd:/etc/nginx/htpasswd:ro

    dockergen:
        image: jwilder/docker-gen
        container_name: webproxy-dockergen
        restart: on-failure:5
        command: -notify-sighup webproxy-nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - ./data/conf.d:/etc/nginx/conf.d
            - ./data/certs:/etc/nginx/certs:ro
            - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: webproxy-letsencrypt
        restart: on-failure:5
        volumes:
            - ./data/conf.d:/etc/nginx/conf.d
            - webproxy-vhost:/etc/nginx/vhost.d
            - webproxy-html:/usr/share/nginx/html
            - ./data/certs:/etc/nginx/certs
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            NGINX_DOCKER_GEN_CONTAINER: webproxy-dockergen
            NGINX_PROXY_CONTAINER: webproxy-nginx

    mysql:
        image: mysql:5.7
        container_name: webproxy-mysql
        restart: on-failure:5
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    webproxy-vhost:
    webproxy-html:

networks:
    default:
        external:
            name: webproxy